// <auto-generated/>
#nullable enable
using System.Resources;

namespace Cioccolato.Gui.Resources.Strings;

internal static class AppStrings
{
    private static ResourceManager? _resourceManager;

    private static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager("Cioccolato.Gui.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);

    public static string WindowTitle => ResourceManager.GetString("WindowTitle")!;
    public static string NewVariety => ResourceManager.GetString("NewVariety")!;
    public static string EnterVarietyName => ResourceManager.GetString("EnterVarietyName")!;
    public static string Add => ResourceManager.GetString("Add")!;
    public static string Varieties => ResourceManager.GetString("Varieties")!;
    public static string Name => ResourceManager.GetString("Name")!;
    public static string CreatedAt => ResourceManager.GetString("CreatedAt")!;
    public static string Remove => ResourceManager.GetString("Remove")!;
    public static string RemoveAll => ResourceManager.GetString("RemoveAll")!;
}
